export const SET_STATION = 'SET_STATION'
export const SET_ORDER_LIST = 'SET_ORDER_LIST'
export const SET_WS = 'SET_WS'
export const SET_RECOMMEND_LIST = 'SET_RECOMMEND_LIST'
export const START_TIMER = 'START_TIMER'
export const RESET_TIMER = 'RESET_TIMER'
export const CLEAR_TIMER = 'CLEAR_TIMER'
export const CHANGE_LOADING = 'CHANGE_LOADING'
